node {
    stage('COMMIT') {
        echo 'The COMMIT stage'
        checkout scm
        sh 'mvn -f ~/OOR/katas/remote/jenkins-mobile-banking/mobilebanking/pom.xml clean test'
    }
    stage('ACCEPTANCE') {
        echo 'The ACCEPTANCE stage'
    }
}