node {
    stage('COMMIT') {
        echo 'The COMMIT stage'
        sh 'mvn -f ~/OOR/katas/local/jenkins-mobile-banking/mobilebanking/pom.xml clean test'
    }
    stage('ACCEPTANCE') {
        echo 'The ACCEPTANCE stage'
        sh 'robot ~/OOR/katas/local/jenkins-mobile-banking/robotframework-webdemo/login_tests'
    }
}